Repository Yeogigallae/Back-End, pull requests merged in 2025-01, with the labels that each got.

#3 [feat] 투표 기능 및 투표 결과 조회 구현
  .DS_Store
  .gitattributes
  .github/TEMPLATE/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/umc/yeogi_gal_lae/CheckServerStatusController.java
  src/main/java/com/umc/yeogi_gal_lae/UmcYeogigallaeApplication.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/dto/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/dto/VoteResponse.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SwaggerConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/exception/BusinessException.java
  src/main/java/com/umc/yeogi_gal_lae/global/exception/GlobalExceptionHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/response/Code.java
  src/main/java/com/umc/yeogi_gal_lae/global/response/Response.java
  src/main/resources/application.yml
  src/test/java/com/umc/yeogi_gal_lae/UmcYeogigallaeApplicationTests.java
Labels: ✨ FEATURE

#5 [feat] 홈화면, 기능별 생성 화면 구현
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/controller/TripPlanController.java
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/domain/TripType.java
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/dto/TripPlanRequestDTO.java
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/repository/TripPlanRepository.java
  src/main/java/com/umc/yeogi_gal_lae/domain/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/domain/user/controller/HomeController.java
  src/main/java/com/umc/yeogi_gal_lae/domain/vote/service/VoteService.java
Labels: ✨ FEATURE

#12 [refactor] 홈화면 Mapper로 로직 분리
  src/main/java/com/umc/yeogi_gal_lae/api/home/controller/HomeController.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/mapper/HomeResponseMapper.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
Labels: ♻️ REFACTOR

#13 [refactor] 투표 기능 및 투표 조회 기능 리팩토링
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/domain/User.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/VoteType.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
Labels: ♻️ REFACTOR, ✨ FEATURE

#19 [feat] 사용자별 여행 및 투표 관리 기능 추가 및 서비스 개선
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/repository/TripPlanRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
Labels: ✨ FEATURE

#22 [refactor] 투표 기능 및 조회 리팩토링
  build.gradle
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/domain/User.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/repository/UserRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/UserService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/AuthenticatedUserUtils.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/common/response/Response.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/BusinessException.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorResponse.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/GlobalExceptionHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR, ✨ FEATURE

#30 [feat] 투표방 생성 및 투표 확정/종료 여부 및 재투표 여부 판단 기능 구현
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/types/Status.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/UserController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/AuthenticatedUserUtils.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/VoteRoom.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRoomRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRoomRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#35 [chore] docker 구축 및 배포 환경 세팅
  Dockerfile
  docker-compose.yml
  src/main/resources/application-prod.yml
Labels: ⚙️ CHORE

#37 [feat] 운영 서버 DB Flyway 마이그레이션 적용
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__Initial_Set.sql
Labels: ✨ FEATURE

#38 [CI/CD] CI/CD 워크플로우 작성
  .github/workflows/yeogigallae-ci-cd.yml
Labels: ⚙️ CHORE, :zap: CI/CD
