Repository Yeogigallae/Back-End, pull requests merged in 2025-02, with the labels that each got.

#40 [feat] 홈 화면 투표 및 여행 조회 구현
  src/main/java/com/umc/yeogi_gal_lae/api/home/controller/HomeController.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/mapper/HomeResponseMapper.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/repository/HomeRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#51 [feat] 로그인 성공 시 Access Tocken을 쿠키 객체에 담아서 반환하는 로직 추가
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/service/JwtService.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handle/Oauth2LoginSuccessHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#43 [refacotr] 방생성 요청시 validation error 처리
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/request/CreateRoomRequest.java
Labels: ♻️ REFACTOR

#56 [chore] main 최신화 전 캐싱 관련하여 배포 설정 추가
  .github/workflows/yeogigallae-ci-cd.yml
  src/main/resources/application.yml
Labels: ⚙️ CHORE

#58 [feature] 로그인 성공 시 Access Tocken을 쿠키 객체에 담아서 반환하는 로직 추가
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/AuthenticatedUserUtils.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handle/Oauth2LoginSuccessHandler.java
  src/main/resources/static/favicon.ico
Labels: ✨ FEATURE

#42 [feature] 알림 기능 구현
  .gitignore
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/Notification.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/NotificationType.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/dto/NotificationDto.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/repository/NotificationRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/common/BaseEntity.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#54 [feature] 방 목록 조회 api 추가
  src/main/java/com/umc/yeogi_gal_lae/api/room/controller/RoomController.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/response/RoomListResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/repository/RoomMemberRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/repository/RoomRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#57 [Refactor] 여행계획 및 홈화면 조회 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/controller/TripPlanController.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/userImage/domain/UserImage.java
  src/main/java/com/umc/yeogi_gal_lae/api/userImage/repository/UserImageRepository.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ♻️ REFACTOR

#66 [refacotr] 친구목록 조회 api 요청값 삭제
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/controller/FriendshipController.java
Labels: ♻️ REFACTOR

#69 [refactor]: endDate 반환형식 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
Labels: ♻️ REFACTOR

#68 [chore] Nginx 웹 서버 구축 Reverse Proxy 적용
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⚙️ CHORE, 📝 DOCS

#70 [feat] & [refactor] 알림 읽음 여부 구현 및 api 요청 방식 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/controller/HomeController.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/Notification.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/repository/NotificationRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/controller/TripPlanController.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ✨ FEATURE

#77 [feat] 여행 정보 불러오기 기능 구현
  src/main/java/com/umc/yeogi_gal_lae/api/room/repository/RoomMemberRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/repository/UserRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
Labels: ✨ FEATURE

#80 [refacotr] 방목록 조회 엔드포인트 오타 수정
  src/main/java/com/umc/yeogi_gal_lae/api/room/controller/RoomController.java
Labels: ♻️ REFACTOR

#81 [refactor] 초대 url 생성 요청값 삭제
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/controller/FriendshipController.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/dto/CreateInviteRequest.java
Labels: ♻️ REFACTOR

#82 [chore] main 최신화 전 DB migration
  src/main/resources/application.yml
  src/main/resources/db/migration/V5__Upgrade_Set.sql
Labels: ⚙️ CHORE, 📝 DOCS

#85 [refactor] tripplan id, type 저장 조회 응답값 요청값 수정
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/Notification.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/dto/NotificationDto.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
Labels: ♻️ REFACTOR

#86 [refactor] 여행 계획 수정
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
Labels: ♻️ REFACTOR

#87 [refactor] 홈화면 dto, converter 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
Labels: ♻️ REFACTOR

#88 [refactor] friendship 비워져 있을 때 목업데이터 반환하도록 수정 & 친구 삭제 api
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/controller/FriendshipController.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/repository/FriendshipRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/service/FriendshipService.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ♻️ REFACTOR

#89 [refactor] 방 get 요청 데이터 없을 시 목업 데이터 반환하도록 수정
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/response/RoomMemberResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
Labels: ♻️ REFACTOR

#90 [refactor] 알림 없을 시 목업 데이터 반환
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
Labels: ♻️ REFACTOR

#94 [chore] dev 최신화
  .gitignore
  build.gradle
  docker-compose.yml
  nginx/nginx.conf
  src/main/java/com/umc/yeogi_gal_lae/CheckServerStatusController.java
  src/main/java/com/umc/yeogi_gal_lae/StaticController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/UserController.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SwaggerConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/WebConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__Initial_Set.sql
  src/main/resources/db/migration/V2__Upgrade_Set.sql
  src/main/resources/db/migration/V3__add_to_ver2_Set.sql
  src/main/resources/db/migration/V4__add_to_ver2_Set.sql
  src/main/resources/db/migration/V5__Upgrade_Set.sql
  src/main/resources/favicon.ico
  src/main/resources/static/index.html
Labels: ⚙️ CHORE

#95 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/controller/AITripPlanController.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/dto/request/ChatCompletionRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/dto/request/OpenAIRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/dto/response/AITripPlanResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/dto/response/ChatCompletionResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/dto/response/OpenAIResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiTripPlan/service/AITripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/controller/FriendshipController.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/repository/FriendshipRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/service/FriendshipService.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/itinerary/controller/ItineraryController.java
  src/main/java/com/umc/yeogi_gal_lae/api/itinerary/converter/ItineraryConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/itinerary/dto/DailyItineraryResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/itinerary/service/ItineraryService.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/Notification.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/dto/NotificationDto.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/repository/PlaceRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/response/RoomMemberResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/OpenAIConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/success/SuccessCode.java
Labels: ⚙️ CHORE

#97 [Refactor] 카카오 로그인 구현
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/repository/FriendshipInviteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/repository/FriendshipRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/repository/RoomMemberRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/repository/RoomRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/repository/TripPlanRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/UserController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/converter/AuthConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/converter/UserConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/request/UserRequestDTO.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/request/UserTokenRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/response/UserInfoResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/response/UserResponseDTO.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/repository/UserRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/UserService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/AuthenticatedUserUtils.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRoomRepository.java
  src/main/java/com/umc/yeogi_gal_lae/global/common/response/BaseResponse.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/RestTemplateConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/AuthHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorStatus.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtAuthenticationToken.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtToken.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtUtil.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/service/JwtService.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/OauthAttributes.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/dto/KakaoDTO.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handle/Oauth2LoginFailureHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handle/Oauth2LoginSuccessHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/oauth2user/CustomOauth2User.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/oauth2user/KakaoOauth2UserInfo.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/oauth2user/Oauth2UserInfo.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/service/CustomOauth2UserService.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/KakaoUtil.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#103 [refactor] application.yml 수정
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#107 [feature] 홈화면, 기능별생성화면 반환값 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanResponse.java
Labels: ✨ FEATURE

#110 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/converter/AICourseConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/controller/BudgetController.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/converter/BudgetConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/domain/Budget.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/BudgetAssignment.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/BudgetResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/DailyBudgetAssignmentResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/repository/BudgetRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/service/BudgetService.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/controller/PlaceController.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/converter/PlaceConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/domain/Place.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/dto/request/PlaceRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/dto/response/AllPlaceResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/dto/response/PlaceResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/service/PlaceService.java
Labels: ⚙️ CHORE

#114 [refactor] 투표 여행 정보 조회 반환값 리팩토링
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteResponse.java
Labels: ♻️ REFACTOR

#115 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/controller/AICourseController.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/converter/AICourseConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/dto/DailyItineraryResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/controller/BudgetController.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/converter/VoteConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/VoteResponse.java
Labels: ⚙️ CHORE

#117 [feat] 로그인 예외처리 추가
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/AuthHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorStatus.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/GlobalExceptionHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtUtil.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/KakaoUtil.java
Labels: ✨ FEATURE

#119 [Refactor] 완료된 투표 조회 반환 값 수정
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/repository/AICourseRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
Labels: ♻️ REFACTOR

#121 [refactor]: 쿠키 크로스사이트 추가
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
Labels: ♻️ REFACTOR

#122 [refactor] redirect uri 수정
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#125 [feat] 사용자의 요청에 따라 동적으로 Redirect URI 설정
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/KakaoUtil.java
  src/main/resources/application.yml
Labels: ✨ FEATURE

#127 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/converter/UserConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/response/UserInfoResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
Labels: ⚙️ CHORE

#130 [feat] 로그인 프론트의 로컬과 배포환경에 따른 동적 쿠키 설정
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
Labels: ✨ FEATURE

#133 [refactor] 스웨거 주석 추가
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
Labels: ♻️ REFACTOR

#134 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/controller/AuthController.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/response/UserInfoResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/service/AuthService.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
Labels: ⚙️ CHORE

#136 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/controller/AICourseController.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/converter/AICourseConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/dto/AICourseIdResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/dto/AICourseItineraryResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/dto/DailyItineraryResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/repository/AICourseRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/service/AICourseService.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/controller/PlaceController.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/converter/PlaceConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/domain/Place.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/dto/PlaceDTO.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/repository/PlaceRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/service/PlaceService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/domain/TripPlan.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanDTO.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/repository/TripPlanRepository.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
Labels: ⚙️ CHORE

#142 [refactor] 로그인 로직 수정
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtAuthenticationFilter.java
Labels: ♻️ REFACTOR

#145 [refactor] 로그인 필터 수정 및 예외처리 추가
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorStatus.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtUtil.java
Labels: ♻️ REFACTOR

#149 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/controller/AICourseController.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/converter/AICourseConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/dto/AICourseItineraryResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/repository/FriendshipRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/friendship/service/FriendshipService.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorStatus.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc/yeogi_gal_lae/global/jwt/JwtUtil.java
Labels: ⚙️ CHORE

#151 [refactor] 여행생성할 때 voteRoomId 반환하도록 수정
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanResponse.java
Labels: ♻️ REFACTOR

#156 [refactor] 엑세스 토큰 시간 변경 및 여행 조회 로직 수정
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/repository/HomeRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#159 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/service/AICourseService.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/controller/BudgetController.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/domain/BudgetType.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/BudgetAssignment.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/BudgetDetailResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/service/BudgetService.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/repository/HomeRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/service/HomeService.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/converter/TripPlanConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/service/TripPlanService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/controller/VoteController.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/SecurityConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: ⚙️ CHORE

#160 [refactor] Redis, QueryDSL를 이용한 투표 기능 동시성 처리 및 성능 개선
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRoomRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/ModuleConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/QueryDslConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/RedisConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: ♻️ REFACTOR

#166 [chore] 운영 서버 최신화
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/com/umc/yeogi_gal_lae/api/budget/controller/BudgetController.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/converter/BudgetConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/dto/BudgetDetailResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/service/BudgetService.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/dto/request/VoteRoomRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/ValidVoteResultService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/ModuleConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/QueryDslConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/config/RedisConfig.java
  src/main/java/com/umc/yeogi_gal_lae/global/error/ErrorCode.java
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: ⚙️ CHORE

#167 [refactor] deleteCookie 크로스사이트 요청 추가
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
Labels: ♻️ REFACTOR

#169 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/notification/dto/NotificationDto.java
  src/main/java/com/umc/yeogi_gal_lae/api/place/dto/request/PlaceRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/request/AddRoomMemberRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/dto/request/CreateRoomRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/tripPlan/dto/TripPlanRequest.java
  src/main/java/com/umc/yeogi_gal_lae/api/user/dto/request/UserRequestDTO.java
  src/main/java/com/umc/yeogi_gal_lae/global/oauth/util/CookieUtil.java
Labels: ⚙️ CHORE

#171 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
Labels: ⚙️ CHORE

#173 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/home/converter/HomeConverter.java
  src/main/java/com/umc/yeogi_gal_lae/api/home/dto/HomeResponse.java
  src/main/java/com/umc/yeogi_gal_lae/api/room/service/RoomService.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/domain/Vote.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/repository/VoteRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/vote/service/VoteService.java
Labels: ⚙️ CHORE

#175 [chore] 운영 서버 최신화
  src/main/java/com/umc/yeogi_gal_lae/api/aiCourse/service/AICourseService.java
  src/main/java/com/umc/yeogi_gal_lae/api/budget/service/BudgetService.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/controller/NotificationController.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/domain/Notification.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/repository/NotificationRepository.java
  src/main/java/com/umc/yeogi_gal_lae/api/notification/service/NotificationService.java
Labels: ⚙️ CHORE
